import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: ['class', '[data-theme="dark"]'],
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './.storybook/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Brand primitives (from handoff)
        grass: {
          50:  'var(--grass-50)',
          100: 'var(--grass-100)',
          200: 'var(--grass-200)',
          300: 'var(--grass-300)',
          400: 'var(--grass-400)',
          500: 'var(--grass-500)',
          600: 'var(--grass-600)',
          700: 'var(--grass-700)',
          800: 'var(--grass-800)',
          900: 'var(--grass-900)',
        },
        gold: {
          50:  'var(--gold-50)',
          100: 'var(--gold-100)',
          300: 'var(--gold-300)',
          400: 'var(--gold-400)',
          500: 'var(--gold-500)',
          700: 'var(--gold-700)',
        },
        magenta: {
          100: 'var(--magenta-100)',
          300: 'var(--magenta-300)',
          500: 'var(--magenta-500)',
          600: 'var(--magenta-600)',
          800: 'var(--magenta-800)',
        },
        cyan: {
          100: 'var(--cyan-100)',
          300: 'var(--cyan-300)',
          500: 'var(--cyan-500)',
          600: 'var(--cyan-600)',
          800: 'var(--cyan-800)',
        },
        ink: {
          50:  'var(--ink-50)',
          100: 'var(--ink-100)',
          200: 'var(--ink-200)',
          300: 'var(--ink-300)',
          400: 'var(--ink-400)',
          500: 'var(--ink-500)',
          600: 'var(--ink-600)',
          700: 'var(--ink-700)',
          800: 'var(--ink-800)',
          900: 'var(--ink-900)',
          950: 'var(--ink-950)',
        },
        // Semantic surfaces (switch with theme)
        bg:         'var(--bg)',
        'bg-elevated': 'var(--bg-elevated)',
        surface:    'var(--surface)',
        'surface-2': 'var(--surface-2)',
        'surface-3': 'var(--surface-3)',
        slot:       'var(--slot)',
        // Foreground
        fg:         'var(--fg)',
        'fg-2':     'var(--fg-2)',
        'fg-3':     'var(--fg-3)',
        'fg-on-brand': 'var(--fg-on-brand)',
        'fg-on-gold':  'var(--fg-on-gold)',
        // Borders
        border:        'var(--border)',
        'border-strong': 'var(--border-strong)',
        ring:          'var(--ring)',
        // Primary
        primary:       'var(--primary)',
        'primary-hover': 'var(--primary-hover)',
        'primary-press': 'var(--primary-press)',
        'on-primary':  'var(--on-primary)',
        // Semantic feedback
        success:       'var(--success)',
        'success-bg':  'var(--success-bg)',
        'success-ink': 'var(--success-ink)',
        error:         'var(--error)',
        'error-bg':    'var(--error-bg)',
        'error-ink':   'var(--error-ink)',
        warning:       'var(--warning)',
        'warning-bg':  'var(--warning-bg)',
        'warning-ink': 'var(--warning-ink)',
        info:          'var(--info)',
        'info-bg':     'var(--info-bg)',
        'info-ink':    'var(--info-ink)',
      },
      fontFamily: {
        display: 'var(--font-display)',
        ui:      'var(--font-ui)',
        mono:    'var(--font-mono)',
      },
      spacing: {
        1:  'var(--sp-1)',
        2:  'var(--sp-2)',
        3:  'var(--sp-3)',
        4:  'var(--sp-4)',
        5:  'var(--sp-5)',
        6:  'var(--sp-6)',
        8:  'var(--sp-8)',
        10: 'var(--sp-10)',
        12: 'var(--sp-12)',
        16: 'var(--sp-16)',
      },
      borderRadius: {
        xs:   'var(--r-xs)',
        sm:   'var(--r-sm)',
        md:   'var(--r-md)',
        lg:   'var(--r-lg)',
        xl:   'var(--r-xl)',
        card: 'var(--r-card)',
        pill: 'var(--r-pill)',
      },
      boxShadow: {
        1: 'var(--sh-1)',
        2: 'var(--sh-2)',
        3: 'var(--sh-3)',
        4: 'var(--sh-4)',
        'glow-grass':   'var(--glow-grass)',
        'glow-magenta': 'var(--glow-magenta)',
        'glow-gold':    'var(--glow-gold)',
      },
      transitionDuration: {
        1: 'var(--dur-1)',
        2: 'var(--dur-2)',
        3: 'var(--dur-3)',
        4: 'var(--dur-4)',
      },
      transitionTimingFunction: {
        standard: 'var(--ease-standard)',
        out:      'var(--ease-out)',
        bounce:   'var(--ease-bounce)',
      },
      screens: {
        sm: '390px',
        md: '600px',
        lg: '900px',
        xl: '1200px',
      },
    },
  },
  plugins: [],
}

export default config
