"""Entry point for the autonomous engineering agent."""

from __future__ import annotations

import asyncio
import logging
import sys

from agent.config import get_github_token, get_issue_body, get_issue_number, get_issue_title
from agent.github_client import branch_exists, comment_issue, commit_and_push, create_branch, create_pull_request
from agent.loop import run_fix_loop
from agent.sensor import parse_issue

# ── Logging setup ────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("agent.main")


async def main() -> None:
    """Orchestrate the full agent pipeline."""

    # ── 1. Read environment ──────────────────────────────────────────────────
    try:
        issue_number = get_issue_number()
        issue_body = get_issue_body()
        issue_title = get_issue_title()
        _ = get_github_token()  # Validate early
    except EnvironmentError as exc:
        logger.critical("Missing environment variable: %s", exc)
        sys.exit(1)

    logger.info("Agent started for issue #%d: %s", issue_number, issue_title)

    # ── 2. Parse issue ───────────────────────────────────────────────────────
    try:
        issue_data = parse_issue(issue_title, issue_number, issue_body)
    except Exception as exc:
        logger.error("Failed to parse issue body: %s", exc)
        await comment_issue(
            issue_number,
            f"🤖 **Agent Error**: Could not parse the issue body.\n\n```\n{exc}\n```",
        )
        sys.exit(1)

    if not issue_data.target_files:
        msg = "No target files specified in the issue — the agent cannot proceed."
        logger.error(msg)
        await comment_issue(issue_number, f"🤖 **Agent Error**: {msg}")
        sys.exit(1)

    # ── 3. Idempotency check ─────────────────────────────────────────────────
    branch_name = f"agent/fix-issue-{issue_number}"
    if await branch_exists(branch_name):
        logger.info("Branch %s already exists — skipping (idempotent)", branch_name)
        return

    # ── 4. Run the fix loop ──────────────────────────────────────────────────
    success, patches = await run_fix_loop(issue_data)

    # ── 5. Handle result ─────────────────────────────────────────────────────
    if success and patches:
        logger.info("Fix succeeded — creating branch and PR")
        try:
            await create_branch(branch_name)
            await commit_and_push(
                branch_name,
                patches,
                f"fix: resolve issue #{issue_number} — {issue_title}",
            )
            pr_url = await create_pull_request(
                branch=branch_name,
                issue_number=issue_number,
                title=f"fix: #{issue_number} — {issue_title}",
                body=(
                    f"## Automated fix for #{issue_number}\n\n"
                    f"This PR was generated by the autonomous engineering agent.\n\n"
                    f"**Issue:** #{issue_number}\n"
                    f"**Files changed:** {', '.join(f'`{p.filename}`' for p in patches)}\n\n"
                    f"Please review the changes carefully before merging.\n\n"
                    f"Closes #{issue_number}"
                ),
            )
            await comment_issue(
                issue_number,
                f"🤖 **Agent**: I've created a fix in {pr_url}.\n\n"
                f"Files modified: {', '.join(f'`{p.filename}`' for p in patches)}.\n\n"
                f"Please review and merge if the changes look correct.",
            )
            logger.info("PR created successfully: %s", pr_url)
        except Exception as exc:
            logger.error("Failed to create PR: %s", exc)
            await comment_issue(
                issue_number,
                f"🤖 **Agent Error**: Tests passed but PR creation failed.\n\n```\n{exc}\n```",
            )
            sys.exit(1)
    else:
        logger.error("Fix loop failed — commenting on issue")
        await comment_issue(
            issue_number,
            (
                f"🤖 **Agent**: I was unable to fix issue #{issue_number} after "
                f"multiple attempts.\n\n"
                f"**Target files:** {', '.join(f'`{f}`' for f in issue_data.target_files)}\n\n"
                f"A human developer may need to investigate this further."
            ),
        )
        sys.exit(1)


def entry() -> None:
    """Sync entry point for ``python -m agent.main``."""
    asyncio.run(main())


if __name__ == "__main__":
    entry()
